In [2]:
import pandas as pd

In [3]:
data_train = pd.read_csv("Train_finish.csv")
data_test = pd.read_csv("Test_finish.csv")

In [4]:
data_train

,DienTich,Phongngu,SoTang,PhongTam,Loai,GiayTo,TinhTrangNoiThat,HuongCuaChinh,HuongBanCong,DacDiem
0,62.0,2.0,1.0,2.0,2,2,1,5,5,1
1,95.0,3.0,35.0,2.0,2,1,2,1,3,1
2,75.0,2.0,5.0,2.0,2,0,3,7,7,1
3,70.0,1.0,7.0,1.0,2,1,2,7,3,1
4,83.0,2.0,25.0,2.0,2,2,2,3,6,1
...,...,...,...,...,...,...,...,...,...,...
24014,53.0,2.0,19.0,1.0,2,1,1,5,4,1
24015,76.0,2.0,1.0,1.0,2,2,2,5,7,1
24016,115.0,2.0,25.0,2.0,2,2,2,3,4,1
24017,82.0,2.0,1.0,2.0,2,2,3,7,3,1
24018,60.0,2.0,18.0,1.0,2,1,2,5,5,1

In [15]:
data_test

       USD
0       83
1      220
2      107
3      166
4      122
...    ...
24014   87
24015   64
24016  137
24017  110
24018   79

[24019 rows x 1 columns]

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [7]:
df= data_train.copy()

In [14]:
df['USD'] = data_test

In [16]:
df

,DienTich,Phongngu,SoTang,PhongTam,Loai,GiayTo,TinhTrangNoiThat,HuongCuaChinh,HuongBanCong,DacDiem,USD
0,62.0,2.0,1.0,2.0,2,2,1,5,5,1,83
1,95.0,3.0,35.0,2.0,2,1,2,1,3,1,220
2,75.0,2.0,5.0,2.0,2,0,3,7,7,1,107
3,70.0,1.0,7.0,1.0,2,1,2,7,3,1,166
4,83.0,2.0,25.0,2.0,2,2,2,3,6,1,122
...,...,...,...,...,...,...,...,...,...,...,...
24014,53.0,2.0,19.0,1.0,2,1,1,5,4,1,87
24015,76.0,2.0,1.0,1.0,2,2,2,5,7,1,64
24016,115.0,2.0,25.0,2.0,2,2,2,3,4,1,137
24017,82.0,2.0,1.0,2.0,2,2,3,7,3,1,110
24018,60.0,2.0,18.0,1.0,2,1,2,5,5,1,79

In [17]:
df['DienTich'] = df['DienTich'].astype(str)
df['USD'] = df['USD'].astype(str)

In [20]:
df['content'] = df[['DienTich','USD']].astype(str).apply(lambda x: '//'.join(x) , axis =1)

In [21]:
df

,DienTich,Phongngu,SoTang,PhongTam,Loai,GiayTo,TinhTrangNoiThat,HuongCuaChinh,HuongBanCong,DacDiem,USD,content
0,62.0,2.0,1.0,2.0,2,2,1,5,5,1,83,62.0//83
1,95.0,3.0,35.0,2.0,2,1,2,1,3,1,220,95.0//220
2,75.0,2.0,5.0,2.0,2,0,3,7,7,1,107,75.0//107
3,70.0,1.0,7.0,1.0,2,1,2,7,3,1,166,70.0//166
4,83.0,2.0,25.0,2.0,2,2,2,3,6,1,122,83.0//122
...,...,...,...,...,...,...,...,...,...,...,...,...
24014,53.0,2.0,19.0,1.0,2,1,1,5,4,1,87,53.0//87
24015,76.0,2.0,1.0,1.0,2,2,2,5,7,1,64,76.0//64
24016,115.0,2.0,25.0,2.0,2,2,2,3,4,1,137,115.0//137
24017,82.0,2.0,1.0,2.0,2,2,3,7,3,1,110,82.0//110
24018,60.0,2.0,18.0,1.0,2,1,2,5,5,1,79,60.0//79

In [65]:
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['content'])

In [66]:
print(tfidf_matrix)

  (0, 418)	0.7422776185195255
  (0, 371)	0.6700924839490305
  (1, 165)	0.7806872785016927
  (1, 438)	0.6249218936680171
  (2, 19)	0.8356133427633377
  (2, 399)	0.5493180694241551
  (3, 102)	0.8235765516038108
  (3, 389)	0.5672051336583401
  (4, 44)	0.7824988042389326
  (4, 418)	0.6226520869351041
  (5, 416)	0.7666326610192395
  (5, 392)	0.6420859467848209
  (6, 28)	0.8500811610902657
  (6, 392)	0.5266517061203029
  (7, 406)	0.6897763324108505
  (7, 19)	0.7240225212283357
  (8, 358)	0.7779271695711734
  (8, 340)	0.6283544531894263
  (9, 298)	1.0
  (10, 414)	0.6656011471554532
  (10, 406)	0.746307652985915
  (11, 296)	0.7315995402885335
  (11, 312)	0.6817346350667587
  (12, 364)	0.681278345937889
  (12, 416)	0.7320244636322847
  :	:
  (24006, 358)	0.7824835152446805
  (24007, 402)	0.7654776194178786
  (24007, 380)	0.6434625196313593
  (24008, 420)	0.5658542373698123
  (24008, 380)	0.8245052953442009
  (24009, 20)	0.8326239570262177
  (24009, 399)	0.5538387366246634
  (24010, 33)	0.7964588358187535
  (24010, 366)	0.6046927507802916
  (24011, 398)	0.7350493705677686
  (24011, 414)	0.6780135860201675
  (24012, 93)	0.7107610020049767
  (24012, 334)	0.7034335775529069
  (24013, 12)	0.7673715650903846
  (24013, 386)	0.6412026833152942
  (24014, 351)	0.7084027982953438
  (24014, 425)	0.7058083843135661
  (24015, 401)	0.7399747962689992
  (24015, 376)	0.672634596855271
  (24016, 64)	0.6792626989379307
  (24016, 32)	0.733895214476534
  (24017, 25)	0.7167593353276004
  (24017, 416)	0.6973206258391734
  (24018, 366)	0.6496320795496059
  (24018, 409)	0.7602487495682282

In [68]:
cosine_similarities =linear_kernel(tfidf_matrix,tfidf_matrix)

In [69]:
print(cosine_similarities)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]

In [40]:
indices = pd.Series(df.index,index=df['content'])
indices

content
62.0//83          0
95.0//220         1
75.0//107         2
70.0//166         3
83.0//122         4
              ...
53.0//87      24014
76.0//64      24015
115.0//137    24016
82.0//110     24017
60.0//79      24018
Length: 24019, dtype: int64

In [50]:
def get_recommend_houses(title,cosine_similarities=cosine_similarities):
    #Lấy index của bộ film theo tiêu đề đưa vào
    idx=indices[title]
    #Lấy điểm tương đồng theo cặp của tất cả các movies theo tiêu đề bộ film đưa vào
    sim_scores = list(enumerate(cosine_similarities[idx]))
    #Sắp xếp các bộ film dựa theo điểm tương đồng
    sim_scores = sorted(sim_scores, key=lambda x: x[0], reverse=True)
    #Lấy điểm của 15 bộ film có độ tương đồng cao nhất
    sim_scores_15 = sim_scores[1:16]
    #Lấy index tương ứng với 15 bộ film này
    movies_index = [i[0] for i in sim_scores_15]
    #trả ra tiêu đề của 15 bộ film
    return df[['DienTich','SoTang','USD']].iloc[movies_index]

In [51]:
get_recommend_houses('62.0//83')

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [64]:
sim_scores1 = list(enumerate(cosine_similarities[indices['62.0//83']]))
sim_scores1 = sorted(sim_scores1, key=lambda x: x[0], reverse=True)
sim_scores1

[(150, array([1., 0., 0., ..., 0., 0., 0.])),
 (149, array([1., 0., 0., ..., 0., 0., 0.])),
 (148, array([1., 0., 0., ..., 0., 0., 0.])),
 (147, array([1., 0., 0., ..., 0., 0., 0.])),
 (146, array([1., 0., 0., ..., 0., 0., 0.])),
 (145, array([1., 0., 0., ..., 0., 0., 0.])),
 (144, array([1., 0., 0., ..., 0., 0., 0.])),
 (143, array([1., 0., 0., ..., 0., 0., 0.])),
 (142, array([1., 0., 0., ..., 0., 0., 0.])),
 (141, array([1., 0., 0., ..., 0., 0., 0.])),
 (140, array([1., 0., 0., ..., 0., 0., 0.])),
 (139, array([1., 0., 0., ..., 0., 0., 0.])),
 (138, array([1., 0., 0., ..., 0., 0., 0.])),
 (137, array([1., 0., 0., ..., 0., 0., 0.])),
 (136, array([1., 0., 0., ..., 0., 0., 0.])),
 (135, array([1., 0., 0., ..., 0., 0., 0.])),
 (134, array([1., 0., 0., ..., 0., 0., 0.])),
 (133, array([1., 0., 0., ..., 0., 0., 0.])),
 (132, array([1., 0., 0., ..., 0., 0., 0.])),
 (131, array([1., 0., 0., ..., 0., 0., 0.])),
 (130, array([1., 0., 0., ..., 0., 0., 0.])),
 (129, array([1., 0., 0., ..., 0., 0., 0.])),
 (128, array([1., 0., 0., ..., 0., 0., 0.])),
 (127, array([1., 0., 0., ..., 0., 0., 0.])),
 (126, array([1., 0., 0., ..., 0., 0., 0.])),
 (125, array([1., 0., 0., ..., 0., 0., 0.])),
 (124, array([1., 0., 0., ..., 0., 0., 0.])),
 (123, array([1., 0., 0., ..., 0., 0., 0.])),
 (122, array([1., 0., 0., ..., 0., 0., 0.])),
 (121, array([1., 0., 0., ..., 0., 0., 0.])),
 (120, array([1., 0., 0., ..., 0., 0., 0.])),
 (119, array([1., 0., 0., ..., 0., 0., 0.])),
 (118, array([1., 0., 0., ..., 0., 0., 0.])),
 (117, array([1., 0., 0., ..., 0., 0., 0.])),
 (116, array([1., 0., 0., ..., 0., 0., 0.])),
 (115, array([1., 0., 0., ..., 0., 0., 0.])),
 (114, array([1., 0., 0., ..., 0., 0., 0.])),
 (113, array([1., 0., 0., ..., 0., 0., 0.])),
 (112, array([1., 0., 0., ..., 0., 0., 0.])),
 (111, array([1., 0., 0., ..., 0., 0., 0.])),
 (110, array([1., 0., 0., ..., 0., 0., 0.])),
 (109, array([1., 0., 0., ..., 0., 0., 0.])),
 (108, array([1., 0., 0., ..., 0., 0., 0.])),
 (107, array([1., 0., 0., ..., 0., 0., 0.])),
 (106, array([1., 0., 0., ..., 0., 0., 0.])),
 (105, array([1., 0., 0., ..., 0., 0., 0.])),
 (104, array([1., 0., 0., ..., 0., 0., 0.])),
 (103, array([1., 0., 0., ..., 0., 0., 0.])),
 (102, array([1., 0., 0., ..., 0., 0., 0.])),
 (101, array([1., 0., 0., ..., 0., 0., 0.])),
 (100, array([1., 0., 0., ..., 0., 0., 0.])),
 (99, array([1., 0., 0., ..., 0., 0., 0.])),
 (98, array([1., 0., 0., ..., 0., 0., 0.])),
 (97, array([1., 0., 0., ..., 0., 0., 0.])),
 (96, array([1., 0., 0., ..., 0., 0., 0.])),
 (95, array([1., 0., 0., ..., 0., 0., 0.])),
 (94, array([1., 0., 0., ..., 0., 0., 0.])),
 (93, array([1., 0., 0., ..., 0., 0., 0.])),
 (92, array([1., 0., 0., ..., 0., 0., 0.])),
 (91, array([1., 0., 0., ..., 0., 0., 0.])),
 (90, array([1., 0., 0., ..., 0., 0., 0.])),
 (89, array([1., 0., 0., ..., 0., 0., 0.])),
 (88, array([1., 0., 0., ..., 0., 0., 0.])),
 (87, array([1., 0., 0., ..., 0., 0., 0.])),
 (86, array([1., 0., 0., ..., 0., 0., 0.])),
 (85, array([1., 0., 0., ..., 0., 0., 0.])),
 (84, array([1., 0., 0., ..., 0., 0., 0.])),
 (83, array([1., 0., 0., ..., 0., 0., 0.])),
 (82, array([1., 0., 0., ..., 0., 0., 0.])),
 (81, array([1., 0., 0., ..., 0., 0., 0.])),
 (80, array([1., 0., 0., ..., 0., 0., 0.])),
 (79, array([1., 0., 0., ..., 0., 0., 0.])),
 (78, array([1., 0., 0., ..., 0., 0., 0.])),
 (77, array([1., 0., 0., ..., 0., 0., 0.])),
 (76, array([1., 0., 0., ..., 0., 0., 0.])),
 (75, array([1., 0., 0., ..., 0., 0., 0.])),
 (74, array([1., 0., 0., ..., 0., 0., 0.])),
 (73, array([1., 0., 0., ..., 0., 0., 0.])),
 (72, array([1., 0., 0., ..., 0., 0., 0.])),
 (71, array([1., 0., 0., ..., 0., 0., 0.])),
 (70, array([1., 0., 0., ..., 0., 0., 0.])),
 (69, array([1., 0., 0., ..., 0., 0., 0.])),
 (68, array([1., 0., 0., ..., 0., 0., 0.])),
 (67, array([1., 0., 0., ..., 0., 0., 0.])),
 (66, array([1., 0., 0., ..., 0., 0., 0.])),
 (65, array([1., 0., 0., ..., 0., 0., 0.])),
 (64, array([1., 0., 0., ..., 0., 0., 0.])),
 (63, array([1., 0., 0., ..., 0., 0., 0.])),
 (62, array([1., 0., 0., ..., 0., 0., 0.])),
 (61, array([1., 0., 0., ..., 0., 0., 0.])),
 (60, array([1., 0., 0., ..., 0., 0., 0.])),
 (59, array([1., 0., 0., ..., 0., 0., 0.])),
 (58, array([1., 0., 0., ..., 0., 0., 0.])),
 (57, array([1., 0., 0., ..., 0., 0., 0.])),
 (56, array([1., 0., 0., ..., 0., 0., 0.])),
 (55, array([1., 0., 0., ..., 0., 0., 0.])),
 (54, array([1., 0., 0., ..., 0., 0., 0.])),
 (53, array([1., 0., 0., ..., 0., 0., 0.])),
 (52, array([1., 0., 0., ..., 0., 0., 0.])),
 (51, array([1., 0., 0., ..., 0., 0., 0.])),
 (50, array([1., 0., 0., ..., 0., 0., 0.])),
 (49, array([1., 0., 0., ..., 0., 0., 0.])),
 (48, array([1., 0., 0., ..., 0., 0., 0.])),
 (47, array([1., 0., 0., ..., 0., 0., 0.])),
 (46, array([1., 0., 0., ..., 0., 0., 0.])),
 (45, array([1., 0., 0., ..., 0., 0., 0.])),
 (44, array([1., 0., 0., ..., 0., 0., 0.])),
 (43, array([1., 0., 0., ..., 0., 0., 0.])),
 (42, array([1., 0., 0., ..., 0., 0., 0.])),
 (41, array([1., 0., 0., ..., 0., 0., 0.])),
 (40, array([1., 0., 0., ..., 0., 0., 0.])),
 (39, array([1., 0., 0., ..., 0., 0., 0.])),
 (38, array([1., 0., 0., ..., 0., 0., 0.])),
 (37, array([1., 0., 0., ..., 0., 0., 0.])),
 (36, array([1., 0., 0., ..., 0., 0., 0.])),
 (35, array([1., 0., 0., ..., 0., 0., 0.])),
 (34, array([1., 0., 0., ..., 0., 0., 0.])),
 (33, array([1., 0., 0., ..., 0., 0., 0.])),
 (32, array([1., 0., 0., ..., 0., 0., 0.])),
 (31, array([1., 0., 0., ..., 0., 0., 0.])),
 (30, array([1., 0., 0., ..., 0., 0., 0.])),
 (29, array([1., 0., 0., ..., 0., 0., 0.])),
 (28, array([1., 0., 0., ..., 0., 0., 0.])),
 (27, array([1., 0., 0., ..., 0., 0., 0.])),
 (26, array([1., 0., 0., ..., 0., 0., 0.])),
 (25, array([1., 0., 0., ..., 0., 0., 0.])),
 (24, array([1., 0., 0., ..., 0., 0., 0.])),
 (23, array([1., 0., 0., ..., 0., 0., 0.])),
 (22, array([1., 0., 0., ..., 0., 0., 0.])),
 (21, array([1., 0., 0., ..., 0., 0., 0.])),
 (20, array([1., 0., 0., ..., 0., 0., 0.])),
 (19, array([1., 0., 0., ..., 0., 0., 0.])),
 (18, array([1., 0., 0., ..., 0., 0., 0.])),
 (17, array([1., 0., 0., ..., 0., 0., 0.])),
 (16, array([1., 0., 0., ..., 0., 0., 0.])),
 (15, array([1., 0., 0., ..., 0., 0., 0.])),
 (14, array([1., 0., 0., ..., 0., 0., 0.])),
 (13, array([1., 0., 0., ..., 0., 0., 0.])),
 (12, array([1., 0., 0., ..., 0., 0., 0.])),
 (11, array([1., 0., 0., ..., 0., 0., 0.])),
 (10, array([1., 0., 0., ..., 0., 0., 0.])),
 (9, array([1., 0., 0., ..., 0., 0., 0.])),
 (8, array([1., 0., 0., ..., 0., 0., 0.])),
 (7, array([1., 0., 0., ..., 0., 0., 0.])),
 (6, array([1., 0., 0., ..., 0., 0., 0.])),
 (5, array([1., 0., 0., ..., 0., 0., 0.])),
 (4, array([1., 0., 0., ..., 0., 0., 0.])),
 (3, array([1., 0., 0., ..., 0., 0., 0.])),
 (2, array([1., 0., 0., ..., 0., 0., 0.])),
 (1, array([1., 0., 0., ..., 0., 0., 0.])),
 (0, array([1., 0., 0., ..., 0., 0., 0.]))]